-- Creation of users table
CREATE TABLE public.users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY,
    username CHARACTER VARYING NOT NULL,
    password CHARACTER VARYING NOT NULL,
    email CHARACTER VARYING NOT NULL,
    PRIMARY KEY (user_id)
);
ALTER TABLE IF EXISTS public.users OWNER to lucaspadapi;
--Creation of clients table
CREATE TYPE client_type AS ENUM ('DETRAN', 'SMTR');
CREATE TYPE client_civil AS ENUM ('single', 'married', 'divorced', 'widowed');
CREATE TYPE client_gender AS ENUM ('male', 'female');
CREATE TABLE public.clients (
    client_cpf INTEGER NOT NULL PRIMARY KEY,
    client_name CHARACTER VARYING NOT NULL,
    client_type client_type NOT NULL,
    client_civil client_civil,
    client_gender client_gender NOT NULL,
    client_phone INT,
    client_email CHARACTER VARYING
);
ALTER TABLE IF EXISTS public.clients OWNER to lucaspadapi;
-- Creation of vehicles table
CREATE TYPE vehicle_category AS ENUM ('owner', 'lease');
CREATE TYPE vehicle_gas AS ENUM (
    'gas',
    'alcohol',
    'flex',
    'gas/gnv',
    'alcohol/gnv',
    'diesel',
    'electric'
);
CREATE TABLE public.vehicles (
    vehicle_sign CHARACTER VARYING NOT NULL PRIMARY KEY,
    vehicle_renavam INTEGER NOT NULL,
    vehicle_fabrication_year DATE NOT NULL,
    vehicle_model_year DATE NOT NULL,
    vehicle_brand CHARACTER VARYING NOT NULL,
    vehicle_model CHARACTER VARYING NOT NULL,
    vehicle_chassi CHARACTER VARYING NOT NULL,
    vehicle_color CHARACTER VARYING NOT NULL,
    vehicle_category vehicle_category NOT NULL,
    vehicle_gas vehicle_gas NOT NULL,
    vehicle_client_cpf INTEGER,
    CONSTRAINT fk_client FOREIGN KEY (vehicle_client_cpf) REFERENCES public.clients (client_cpf) ON UPDATE CASCADE ON DELETE NO ACTION
);
ALTER TABLE IF EXISTS public.vehicles OWNER to lucaspadapi;
-- Creation of services table
CREATE TABLE public.services (
    service_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name CHARACTER VARYING NOT NULL,
    service_description CHARACTER VARYING NOT NULL,
    service_price INTEGER NOT NULL
);
ALTER TABLE IF EXISTS public.services OWNER to lucaspadapi;
-- Creation of orders table
CREATE TABLE public.orders (
    order_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_service_id INTEGER NOT NULL,
    order_client_cpf INTEGER NOT NULL,
    order_vehicle_sign CHARACTER VARYING,
    CONSTRAINT fk_order_service FOREIGN KEY (order_service_id) REFERENCES public.services (service_id) ON UPDATE CASCADE ON DELETE NO ACTION,
    CONSTRAINT fk_order_client FOREIGN KEY (order_client_cpf) REFERENCES public.clients (client_cpf) ON UPDATE CASCADE ON DELETE NO ACTION,
    CONSTRAINT fk_order_vehicle FOREIGN KEY (order_vehicle_sign) REFERENCES public.vehicles (vehicle_sign) ON UPDATE CASCADE ON DELETE NO ACTION
);
ALTER TABLE IF EXISTS public.orders OWNER to lucaspadapi;